name: todo_app
description: A simple To-Do List app using Flutter and Riverpod
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.0

flutter:
  uses-material-design: true
